version: '3'

services:
  gammu:
    build: ./dockers/gammu-smsd
    container_name: firessms-gammu
    volumes:
      - ./configs/gammurc:/etc/gammurc
      - ./configs/smsdrc:/etc/smsd/smsdrc
      - ./volumes/database:/var/spool/gammu/
#    command: tail -f /dev/null
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - LIBUSB_DEBUG=0
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    device_cgroup_rules:
      - 'c 188:0 rmw'
    privileged: true
    restart: always

  api:
    build: ./dockers/api
    container_name: firessms-api
    ports:
      - "8080:8080"
    depends_on:
      - gammu
    environment:
      - API_TOKEN=${API_TOKEN}
    volumes:
      - ./volumes/database:/var/lib/gammu/
    restart: always
networks:
  default:
    driver: bridge

